/*
 * This source file was generated by the Gradle 'init' task
 */
package lab1.task2;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.List;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void testAlreadySortedArray() {
    int[] input = { 1, 2, 3 };

    BubbleSort.Result result = BubbleSort.sort(input);

    assertArrayEquals(new int[] { 1, 2, 3 }, result.sortedArray);

    List<String> expectedTrace = List.of(
        "T0",
        "T1", "T2", "T3",
        "T2", "T3",
        "T1", "T2", "T3",
        "T5");

    assertEquals(expectedTrace, result.trace);
  }

  @Test
  void testReverseSortedArray() {
    int[] input = { 3, 2, 1 };

    BubbleSort.Result result = BubbleSort.sort(input);

    assertArrayEquals(new int[] { 1, 2, 3 }, result.sortedArray);

    List<String> expectedTrace = List.of(
        "T0",
        "T1", "T2", "T3", "T4",
        "T2", "T3", "T4",
        "T1", "T2", "T3", "T4",
        "T5");

    assertEquals(expectedTrace, result.trace);
  }

  @Test
  void testSingleElement() {
    int[] input = { 1 };

    BubbleSort.Result result = BubbleSort.sort(input);

    assertArrayEquals(new int[] { 1 }, result.sortedArray);

    List<String> expectedTrace = List.of(
        "T0",
        "T5");

    assertEquals(expectedTrace, result.trace);
  }

  @Test
  void testEmptyArray() {
    int[] input = {};

    BubbleSort.Result result = BubbleSort.sort(input);

    assertArrayEquals(new int[] {}, result.sortedArray);

    List<String> expectedTrace = List.of(
        "T0",
        "T5");

    assertEquals(expectedTrace, result.trace);
  }
}
