from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path

import matplotlib.pyplot as plt


def load_points(csv_path: Path) -> tuple[list[float], list[float]]:
    xs: list[float] = []
    ys: list[float] = []

    with csv_path.open(newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            x = row.get("x", "").strip()
            y = row.get("y", "").strip()
            if not x or not y:
                continue
            xs.append(float(x))
            ys.append(float(y))

    return xs, ys


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Plot a CSV generated by App.kt/CSVGraphWriter."
    )
    parser.add_argument(
        "csv_path",
        nargs="?",
        default="plots/MainFunction.csv",
        help="Path to CSV file generated by the app",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Optional output image path. If omitted, the plot is shown interactively.",
    )
    args = parser.parse_args()

    csv_path = Path(args.csv_path)
    xs, ys = load_points(csv_path)

    if not xs:
        raise SystemExit(f"No plottable points found in {csv_path}")

    min_y = min(filter(lambda x: not math.isnan(x), ys))
    max_y = max(filter(lambda x: not math.isnan(x), ys))

    y_lower_limit = max(min_y - 0.5, -10)
    y_upper_limit = min(max_y + 0.5, 10)

    plt.figure(figsize=(12, 6))
    plt.plot(xs, ys, linewidth=1.2, color="#004c6d")
    plt.title(csv_path.stem)
    plt.xlabel("x")
    plt.ylabel("y")
    plt.ylim(y_lower_limit, y_upper_limit)
    plt.grid(True, alpha=0.25)
    plt.tight_layout()

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(output_path, dpi=150)
    else:
        plt.show()


if __name__ == "__main__":
    main()
