/*
 * This source file was generated by the Gradle 'init' task
 */
package lab1.task3;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("программирование 1 курс лоликонщик отбитый")
class AppTest {

  private Person laughingMan;
  private Person girl;
  private Location bar;
  private Scenario scenario;
  private ChemicalComposition humanComposition;

  @BeforeEach
  void setUp() {
    laughingMan = new Person("человек, громко смеявшийся");
    girl = new Person("девушка");
    bar = new Location("бар");

    bar.enter(laughingMan);
    bar.enter(girl);

    scenario = new Scenario(bar);

    // водород, озон, оксид углерода
    Map<String, Double> elements = new HashMap<>();
    elements.put("H2", 40.0);
    elements.put("O3", 30.0);
    elements.put("CO", 30.0);
    humanComposition = new ChemicalComposition(elements);
  }

  @Test
  @DisplayName("девушка испытывает сильную ненависть к смеющемуся человеку")
  void girlFeelsHatredTowardsLaughingMan() {
    girl.feel(laughingMan, Emotion.hatred());

    assertTrue(girl.hasStrongNegativeEmotionTowards(laughingMan));
    assertEquals(Emotion.Type.NEGATIVE, girl.getEmotionTowards(laughingMan).getType());
    assertEquals(Emotion.Intensity.EXTREME, girl.getEmotionTowards(laughingMan).getIntensity());
  }

  @Test
  @DisplayName("смееющийся человек находится в баре вместе с девушкой")
  void bothPersonsInBar() {
    assertTrue(bar.getOccupants().contains(laughingMan));
    assertTrue(bar.getOccupants().contains(girl));
    assertEquals(2, bar.getOccupants().size());
  }

  @Test
  @DisplayName("испарение человека через 1.5 минуты")
  void manEvaporatesAfter90Seconds() {
    Duration evaporationTime = Duration.ofSeconds(90);
    EvaporationEvent event = new EvaporationEvent(laughingMan, evaporationTime, humanComposition);
    scenario.scheduleEvaporation(event);

    assertFalse(laughingMan.isEvaporated());

    scenario.advanceTime(evaporationTime);

    assertTrue(laughingMan.isEvaporated());
    assertNotNull(laughingMan.getCompositionAfterEvaporation());
    assertTrue(laughingMan.getCompositionAfterEvaporation().containsElement("H2"));
    assertTrue(laughingMan.getCompositionAfterEvaporation().containsElement("O3"));
    assertTrue(laughingMan.getCompositionAfterEvaporation().containsElement("CO"));
  }

  @Test
  @DisplayName("оба человека испаряются одновременно")
  void bothPersonsEvaporateSimultaneously() {
    Duration evaporationTime = Duration.ofSeconds(90);

    scenario.scheduleEvaporation(
        new EvaporationEvent(laughingMan, evaporationTime, humanComposition));
    scenario.scheduleEvaporation(
        new EvaporationEvent(girl, evaporationTime, humanComposition));

    scenario.advanceTime(evaporationTime);

    assertTrue(laughingMan.isEvaporated());
    assertTrue(girl.isEvaporated());
    assertEquals(scenario.getCurrentTime(), evaporationTime);
  }

  @Test
  @DisplayName("невозможно испарить человека дважды")
  void cannotEvaporateTwice() {
    girl.evaporate(humanComposition);
    assertTrue(girl.isEvaporated());

    assertThrows(IllegalStateException.class, () -> {
      girl.evaporate(humanComposition);
    });
  }

  @Test
  @DisplayName("валидация химического состава (сумма долей = 100%)")
  void chemicalCompositionValidation() {
    Map<String, Double> validComposition = Map.of(
        "H2", 50.0,
        "O3", 50.0);
    assertDoesNotThrow(() -> new ChemicalComposition(validComposition));

    Map<String, Double> invalidComposition = Map.of(
        "H2", 30.0,
        "O3", 30.0);
    assertThrows(IllegalArgumentException.class, () -> new ChemicalComposition(invalidComposition));
  }

  @Test
  @DisplayName("девушка слишком занята собственным испарением, чтобы заметить испарение другого")
  void girlTooBusyToNoticeOthersEvaporation() {
    Duration evaporationTime = Duration.ofSeconds(90);

    scenario.scheduleEvaporation(
        new EvaporationEvent(laughingMan, evaporationTime, humanComposition));
    scenario.scheduleEvaporation(
        new EvaporationEvent(girl, evaporationTime, humanComposition));

    scenario.advanceTime(evaporationTime);

    assertTrue(laughingMan.isEvaporated());
    assertTrue(girl.isEvaporated());

    assertFalse(girl.toString().contains("noticed"));
  }
}