/*
 * This source file was generated by the Gradle 'init' task
 */
package lab1.task3.domain;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import lab1.task3.domain.command.AttemptResult;
import lab1.task3.domain.command.LiftAction;
import lab1.task3.domain.command.Order;
import lab1.task3.domain.equipment.Tank;
import lab1.task3.domain.personnel.Commander;
import lab1.task3.domain.personnel.Soldier;
import lab1.task3.domain.personnel.Squad;
import lab1.task3.domain.simulation.LiftingAttemptTask;
import lab1.task3.domain.simulation.SimulationEngine;

class AppTest {
  private SimulationEngine engine;
  private Commander commander;
  private Tank secretTank;
  private Order liftOrder;
  private Squad activeSquad;

  @BeforeEach
  void setUp() {
    engine = new SimulationEngine();
    commander = new Commander("Товарищ командир");
    secretTank = new Tank("T-90", "Новый секретный танк", 46000, 4);
    liftOrder = new Order(new LiftAction(), secretTank);
    activeSquad = new Squad();
  }

  @Test
  void shouldSimulateTankLiftingJoke() {
    Soldier petrov = new Soldier("Петров", 100);
    Soldier sidorov = new Soldier("Сидоров", 100);
    Soldier ivanov = new Soldier("Иванов", 100);

    // Петров. Подними танк.
    assertDoesNotThrow(() -> commander.giveOrder(liftOrder, petrov));
    activeSquad.addSoldier(petrov);
    LiftingAttemptTask attempt1 = new LiftingAttemptTask(liftOrder, activeSquad);

    engine.scheduleTask(attempt1);
    engine.runNext(); // Петров тужится, пыжится...

    assertEquals(AttemptResult.FAILURE, attempt1.getLastResult()); // ...не поднять.

    // Сидоров, помоги Петрову.
    assertDoesNotThrow(() -> commander.giveOrder(liftOrder, sidorov));
    activeSquad.addSoldier(sidorov);
    LiftingAttemptTask attempt2 = new LiftingAttemptTask(liftOrder, activeSquad);

    engine.scheduleTask(attempt2);
    engine.runNext(); // Пытаются вдвоем...

    assertEquals(AttemptResult.FAILURE, attempt2.getLastResult()); // ...та же ситуация.

    // Иванов, помогай.
    assertDoesNotThrow(() -> commander.giveOrder(liftOrder, ivanov));
    activeSquad.addSoldier(ivanov);
    LiftingAttemptTask attempt3 = new LiftingAttemptTask(liftOrder, activeSquad);

    engine.scheduleTask(attempt3);
    engine.runNext(); // Пыхтят втроем...

    assertEquals(AttemptResult.FAILURE, attempt3.getLastResult()); // ...Поднять не могут.

    // А ... вы хотели? Сорок шесть тонн...
    assertTrue(secretTank.getWeightKg() > activeSquad.getTotalStrength());
    assertEquals(46000, secretTank.getWeightKg());
    assertEquals(300, activeSquad.getTotalStrength());
    assertEquals(15000, engine.getCurrentTime(), "3 attempts 5s each (15000ms)");
  }
}