/*
 * This source file was generated by the Gradle 'init' task
 */
package lab1.task1;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.junit.jupiter.params.provider.ValueSource;

import lab1.task1.utils.Trig;

class AppTest {
  private static final double ABSOLUTE_EPSILON = 1e-12;
  private static final double RELATIVE_EPSILON = 1e-10;

  // private static void assertApproximatelyEqual(double expected, double actual,
  // double x) {
  // double absError = Math.abs(actual - expected);
  // double relError = absError / (Math.abs(expected) + 1e-15);
  // boolean ok = absError < ABSOLUTE_EPSILON || relError < RELATIVE_EPSILON;
  // assertTrue(ok, String.format(
  // "x = %.6f: expected = %.15f, actual = %.15f, abs error = %.2e, rel error =
  // %.2e",
  // x, expected, actual, absError, relError));
  // }

  // base cases
  @Test
  @DisplayName("tan(0) = 0")
  void tan_Zero_ReturnsSignedZero() {
    assertEquals(0.0, Trig.tan(0.0, 10), ABSOLUTE_EPSILON);
    assertEquals(-0.0, Trig.tan(-0.0, 10), ABSOLUTE_EPSILON);
    assertTrue(Double.compare(Trig.tan(-0.0, 10), -0.0) == 0);
  }

  @ParameterizedTest
  @CsvSource({
      "0.1,   0.10033467208545055,  8",
      "0.3,   0.30933624960962325, 10",
      "0.5,   0.5463024898437905,  12",
      "0.7853981633974483, 1.0, 18", // π/4
      "0.5235987755982988, 0.5773502691896257, 15", // π/6
      "1.0471975511965976, 1.7320508075688767, 30" // π/3
  })
  @DisplayName("test known values of tan(x)")
  void tan_KnownValues_Accurate(double x, double expected, int n) {
    double result = Trig.tan(x, n);
    // assertApproximatelyEqual(expected, result, x);
    assertEquals(expected, result, 1e-10,
        String.format("tan(%.6f) should be approximately %.15f but was %.15f", x, expected, result));
  }

  // corner values
  @ParameterizedTest
  @ValueSource(doubles = { Double.NaN, Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY })
  @DisplayName("Special values return NaN")
  void tan_SpecialValues_ReturnsNaN(double special) {
    assertTrue(Double.isNaN(Trig.tan(special, 20)));
  }

  @Test
  @DisplayName("argument close to π/2 returns inf")
  void tan_NearPole_ReturnsLargeValue() {
    double nearPole = Math.PI / 2 - 1e-6;
    double result = Trig.tan(nearPole, 30);
    assertTrue(result > 1e5, "tan(π/2 - 1e-6) must be > 1e5, but was: " + result);
  }

  // math properties
  @ParameterizedTest
  @ValueSource(doubles = { 0.1, 0.3, 0.5, 0.7, 1.0 })
  @DisplayName("odd fn: tan(-x) = -tan(x)")
  void tan_IsOddFunction(double x) {
    double pos = Trig.tan(x, 20);
    double neg = Trig.tan(-x, 20);
    assertEquals(-pos, neg, ABSOLUTE_EPSILON);
  }

  @ParameterizedTest
  @CsvSource({
      "0.5, 3.641592653589793", // 0.5 + π
      "1.0, 4.141592653589793", // 1.0 + π
      "-0.7, 2.441592653589793" // -0.7 + π
  })
  @DisplayName("periodicity: tan(x + π) = tan(x)")
  void tan_PeriodicityPi(double x, double xPlusPi) {
    double base = Trig.tan(x, 20);
    double shifted = Trig.tan(xPlusPi, 20);
    assertEquals(base, shifted, ABSOLUTE_EPSILON);
  }

  // compare to std
  @ParameterizedTest
  @CsvSource({
      "0.0", "0.1", "0.25", "0.5", "0.75", "1.0", "1.2", "1.4",
      "-0.1", "-0.5", "-1.0", "-1.3"
  })
  @DisplayName("compare to Math.tan() for |x| < π/2")
  void tan_CompareWithMathTan(double x) {
    if (Math.abs(Math.abs(x) - Math.PI / 2) < 0.1)
      return;

    double custom = Trig.tan(x, 20);
    double standard = Math.tan(x);
    assertEquals(custom, standard, ABSOLUTE_EPSILON,
        String.format("tan(%.6f) should be approximately %.15f but was %.15f", x, standard, custom));
  }
}
